version: '3'
services: 

    app:
        build: .
        image: app:1.0.0
        volumes: 
            - ./client:/app/client
            - ./server:/app/server
        ports: 
            - 8080:80
